apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bwf22vhod-go
  janus-idp.io/tekton: bwf22vhod-go
  backstage.io/kubernetes-id: bwf22vhod-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bwf22vhod-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
